### ISSUE TITLE
mkdocs crash

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/wiki_template#18]
```
ERROR    -  Error building page 'Environment variables.md': list index out of range
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 10[55](https://github.com/hannesdelbeke/bqt-wiki/actions/runs/5360980958/jobs/9726558702#step:12:56), in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 16[57](https://github.com/hannesdelbeke/bqt-wiki/actions/runs/5360980958/jobs/9726558702#step:12:58), in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/click/core.py", line 7[60](https://github.com/hannesdelbeke/bqt-wiki/actions/runs/5360980958/jobs/9726558702#step:12:61), in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x[64](https://github.com/hannesdelbeke/bqt-wiki/actions/runs/5360980958/jobs/9726558702#step:12:65)/lib/python3.11/site-packages/mkdocs/__main__.py", line 277, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/mkdocs/commands/build.py", line 226, in _build_page
    context = config.plugins.run_event(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 90, in on_page_context
    self.search_index.add_entry_from_context(page)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 143, in add_entry_from_context
    parser.feed(page.content)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/html/parser.py", line 1[72](https://github.com/hannesdelbeke/bqt-wiki/actions/runs/5360980958/jobs/9726558702#step:12:73), in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/html/parser.py", line 413, in parse_endtag
    self.handle_endtag(elem)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 417, in handle_endtag
    elif data[-1].isspace() and data[-2] == f"<{tag}>":
                                ~~~~^^^^
IndexError: list index out of range
Error: Process completed with exit code 1.
```

**Comment by hannesdelbeke** [comment]
[Environment variables.md](https://github.com/hannesdelbeke/wiki_template/files/11853547/Environment.variables.md)
file it crashed on
